name: check_run
on: 
  workflow_run:
    workflows: ["node_dev"]
    types: 
      - completed
      - requested
jobs:
  echo_event :
    runs-on: ubuntu-latest

    steps:
    - name: ref
      run: echo ${{ github.ref }}

    - name: event
      run: "echo '${{ toJSON(github.event) }}'"

    - name: event_name
      run: echo ${{ github.event_name }}

    - name: event_path
      run: echo ${{ github.event_path }}
