name: noed_env
on: 
  push:
    branches-ignore:
      - main
  release:
    types:
      - published
      - prereleased

jobs:
  echo_event :
   runs-on: ubuntu-latest

   steps:
   - name: event
   - run: echo ${{ github.event }}

   steps:
   - name: event_name
   - run: echo ${{ github.event_name }}

   steps:
   - name: event_path
   - run: echo ${{ github.event_path }}

