name: noed_env
on: 
  # push:
  #   branches-ignore:
  #     - main
  release:
    types: [prereleased]


jobs:
  echo_event :
    runs-on: ubuntu-latest

    steps:
    - name: ref
      run: echo ${{ github.ref }}

    - name: event
      run: echo ${{ github.event }}

    - name: event_name
      run: echo ${{ github.event_name }}

    - name: event_path
      run: echo ${{ github.event_path }}
